# docker-compose.yml

version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=sqlite:///./travel_app.db
      # Add other environment variables here if needed

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend

