name: CI/CD Pipeline for Lab App

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Build and Push Backend Image
        run: |
          docker build -f Dockerfile.backend -t registry.digitalocean.com/fortamosapp/lab-app-backend:${{ github.sha }} .
          docker push registry.digitalocean.com/fortamosapp/lab-app-backend:${{ github.sha }}

      - name: Build and Push Frontend Image
        run: |
          docker build -f frontend/Dockerfile --build-arg REACT_APP_API_URL=http://${{ secrets.SSH_HOST }}:8000 -t registry.digitalocean.com/fortamosapp/lab-app-frontend:${{ github.sha }} ./frontend
          docker push registry.digitalocean.com/fortamosapp/lab-app-frontend:${{ github.sha }}
          
      - name: Deploy to Droplet
        uses: appleboy/ssh-action@master
        env:
          # Define variables to be used in the runner environment
          DOCR_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          BACKEND_IMAGE_TAG: ${{ github.sha }}
          FRONTEND_IMAGE_TAG: ${{ github.sha }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Pass the variables to the remote SSH script
          envs: DOCR_TOKEN,BACKEND_IMAGE_TAG,FRONTEND_IMAGE_TAG
          script: |
            # Exit script on any error
            set -euo pipefail
            # Print each command before executing
            set -x

            # Determine the application directory based on the user
            USERNAME="$(whoami)"
            if [ "$USERNAME" = "root" ]; then
              APP_DIR="root/applab"
            else
              # Prefer /opt/applab for system-wide access
              APP_DIR="/opt/applab"
              sudo mkdir -p "$APP_DIR"
              sudo chown -R "$USERNAME":"$USERNAME" "$APP_DIR"
            fi

            mkdir -p "$APP_DIR"
            cd "$APP_DIR"

            # Ensure envsubst command is available for variable substitution
            if ! command -v envsubst >/dev/null 2>&1; then
              sudo apt-get update -y
              sudo apt-get install -y gettext-base
            fi

            # Log in to DigitalOcean Container Registry to pull images
            echo "$DOCR_TOKEN" | docker login -u doctl --password-stdin registry.digitalocean.com

            # Render the compose file with the new image tags
            # The environment variables are passed from the 'envs' input above
            envsubst < docker-compose.template.yml > docker-compose.yml

            # Pull the latest images and restart the services
            docker compose pull
            docker compose up -d --remove-orphans

